name: Build & Deploy JupyterLite

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install JupyterLite + deps
        run: |
          python -m pip install --upgrade pip
          # Core + Pyodide (Pyolite) kernel
          pip install "jupyterlite==0.6.4" "jupyterlite-pyolite-kernel==0.6.4"
          # Needed so the contents/ folder is copied during build
          pip install "jupyter_server>=2,<3"
          # Widgets support
          pip install "ipywidgets>=8,<9" "jupyterlab_widgets>=3,<4"
          # Optional niceties
          pip install "jupyterlab_server>=2,<3" "libarchive-c"

      - name: Build JupyterLite site
        env:
          REPO_NAME: ${{ github.event.repository.name }}
        run: |
          jupyter lite build --contents content --output-dir _output --base-url "/${{ env.REPO_NAME }}/"

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: _output
          force_orphan: true
